"""Initial schema creation

Revision ID: c3401a311e68
Revises: 
Create Date: 2026-08-24 20:07:27.422529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3401a311e68'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_systems',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('system_type', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('latency_budget_ms', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_systems_name'), 'ai_systems', ['name'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('metadata_json', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource'), 'audit_logs', ['resource'], unique=False)
    op.create_table('interactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ai_system_id', sa.String(length=36), nullable=False),
    sa.Column('user_input', sa.String(length=4000), nullable=False),
    sa.Column('response', sa.String(length=4000), nullable=False),
    sa.Column('context', sa.String(length=4000), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ai_system_id'], ['ai_systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_ai_system_id'), 'interactions', ['ai_system_id'], unique=False)
    op.create_index(op.f('ix_interactions_created_at'), 'interactions', ['created_at'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ai_system_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('risk_threshold', sa.Integer(), nullable=False),
    sa.Column('human_review_threshold', sa.Integer(), nullable=False),
    sa.Column('block_threshold', sa.Integer(), nullable=False),
    sa.Column('privacy_threshold', sa.Integer(), nullable=False),
    sa.Column('bias_threshold', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ai_system_id'], ['ai_systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_ai_system_id'), 'policies', ['ai_system_id'], unique=False)
    op.create_table('agent_traces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('interaction_id', sa.String(length=36), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('component', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('input_data', sa.String(length=4000), nullable=True),
    sa.Column('output_data', sa.String(length=4000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_traces_interaction_id'), 'agent_traces', ['interaction_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('interaction_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_created_at'), 'incidents', ['created_at'], unique=False)
    op.create_index(op.f('ix_incidents_interaction_id'), 'incidents', ['interaction_id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('interaction_id', sa.String(length=36), nullable=False),
    sa.Column('overall_risk_score', sa.Integer(), nullable=False),
    sa.Column('overall_risk_level', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.String(length=20), nullable=False),
    sa.Column('privacy_score', sa.Integer(), nullable=False),
    sa.Column('privacy_findings', sa.String(length=2000), nullable=True),
    sa.Column('safety_score', sa.Integer(), nullable=False),
    sa.Column('safety_findings', sa.String(length=2000), nullable=True),
    sa.Column('bias_score', sa.Integer(), nullable=False),
    sa.Column('bias_findings', sa.String(length=2000), nullable=True),
    sa.Column('hallucination_score', sa.Integer(), nullable=False),
    sa.Column('hallucination_findings', sa.String(length=2000), nullable=True),
    sa.Column('decision_action', sa.String(length=30), nullable=False),
    sa.Column('decision_reason', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessments_interaction_id'), 'risk_assessments', ['interaction_id'], unique=True)
    op.create_table('interventions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('reviewer', sa.String(length=100), nullable=False),
    sa.Column('outcome', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interventions_incident_id'), 'interventions', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interventions_incident_id'), table_name='interventions')
    op.drop_table('interventions')
    op.drop_index(op.f('ix_risk_assessments_interaction_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_incidents_interaction_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_created_at'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_agent_traces_interaction_id'), table_name='agent_traces')
    op.drop_table('agent_traces')
    op.drop_index(op.f('ix_policies_ai_system_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_interactions_created_at'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_ai_system_id'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_index(op.f('ix_audit_logs_resource'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_ai_systems_name'), table_name='ai_systems')
    op.drop_table('ai_systems')
    # ### end Alembic commands ###
